# Generated by Django 5.1.2 on 2024-11-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPcrudPerson', '0003_alter_persona_numero_documento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='Hobbie',
            new_name='hobbie',
        ),
    ]
